### ISSUE TITLE
Could not open piped fork stream more the 20k

### ISSUE THREAD

**Issue by k-okada** [euslisp/EusLisp#79] opened 2015-01-04 02:47 UTC
Reported by @Kindsenior

It seems there are limitation in numbers if piped fork streams
```
(setq *p* (piped-fork "bash"))
(progn (setq i 0) (do-until-key (format *p* "ls~%") (warn " ~s" i) (incf i)))
```

~~I doubt that it forget to close file stream.~~
There might be limitation in read/write stream??

**Comment by garaemon** [comment] 2015-01-04 03:35
PIPE has limited buffer size on POSIX system (see [this topic](http://stackoverflow.com/questions/4624071/pipe-buffer-size-is-4k-or-64k)).
If write buffer (child process -> parent process) exceeds the limit, the child process will hang at the point of writing something to the buffer.

So, in order to avoid this problem, what we can do is just call `(read *p*)`. It's not a bug of euslisp or POSIX.

**Comment by garaemon** [comment] 2015-01-05 03:28
I think it's ok to close this issue.

**Closed** 2015-01-05 09:44 UTC
